# Generated by Django 2.0.3 on 2018-05-06 11:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover_pic', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField()),
                ('url', models.SlugField(blank=True, null=True)),
                ('category_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('in_nav', models.BooleanField(default=0)),
                ('in_footer', models.BooleanField(default=0)),
                ('unlisted', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('cover_pic', models.CharField(blank=True, max_length=500, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('pub_date', models.DateTimeField()),
                ('view_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('url', models.CharField(blank=True, max_length=600, null=True)),
                ('unlisted', models.BooleanField(default=0)),
                ('last_modified', models.DateTimeField()),
                ('is_page', models.BooleanField(default=0)),
                ('in_nav', models.BooleanField(default=0)),
                ('in_footer', models.BooleanField(default=0)),
                ('keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('social', models.BooleanField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.User')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
    ]
