# Generated by Django 2.0.3 on 2018-05-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.BooleanField(default=1)),
                ('email', models.EmailField(max_length=254)),
                ('reg_date', models.DateTimeField()),
                ('display_name', models.CharField(max_length=30)),
                ('last_modified', models.DateTimeField()),
                ('user_pic', models.CharField(max_length=250)),
            ],
        ),
    ]
